apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: "{{ .Release.Namespace }}"
type: kubernetes.io/tls
data:
  tls.crt: "{{ .Values.tls.crt | b64enc }}"
  tls.key: "{{ .Values.tls.key | b64enc }}"
