apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
data:
  TOKEN: {{ .Values.bot_token | b64enc }}
  REDIS_USERNAME_AND_PASSWORD: {{ .Values.redis_username_and_password | b64enc }}