apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  TOKEN: "{{ .Values.bot.token | b64enc }}"
  REDIS_PASSWORD: "{{ .Values.redis.password | b64enc }}"
  MONGO_USERNAME: "{{ .Values.mongo.username | b64enc }}"
  MONGO_PASSWORD: "{{ .Values.mongo.password | b64enc }}"
