apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  TOKEN: {{ .Values.bot.token | b64enc }}
  REDIS_USERNAME_AND_PASSWORD: {{ .Values.redis.username_and_password | b64enc }}