apiVersion: /v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: {{ .Release.Namespace }}
data:
  MONGO_USERNAME: {{ .Values.mongo_username | b64enc }}
  MONGO_PASSWORD: {{ .Values.mongo_password | b64enc }}