apiVersion: /v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: "{{ .Release.Namespace }}"
data:
  username: "{{ .Values.mongo.username | b64enc }}"
  password: "{{ .Values.mongo.password | b64enc }}"
