apiVersion: v1
kind: Service
metadata:
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Release.Name }}-standalone"
  name: "{{ .Release.Name }}-service"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: "{{ .Release.Name }}-standalone"
