apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-pv"
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mongo
