apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: "{{ .Release.Namespace }}"
data:
  HOSTNAME: matchmakerbot.net
  MONGO_HOST: mongo-service.mongo.svc.cluster.local
