apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  namespace: "{{ .Release.Namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - name: "{{ .Release.Name }}"
          image: "ghcr.io/matchmakerbot/{{ .Release.Name }}:latest"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-secret"
            - configMapRef:
                name: "{{ .Release.Name }}-config"
          readinessProbe:
            httpGet:
              path: /api/v1/healthz
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /api/v1/healthz
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 2
