apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  namespace: "{{ .Release.Namespace }}"
data:
  COOKIES_TOKEN: "{{ .Values.cookies.token | b64enc }}"
  DISCORD_BOT_TOKEN: "{{ .Values.discord.bot.token | b64enc }}"
  DISCORD_CLIENT_ID: "{{ .Values.discord.client.id | b64enc }}"
  DISCORD_CLIENT_SECRET: "{{ .Values.discord.client.secret | b64enc }}"
  MONGO_PASSWORD: "{{ .Values.mongo.password | b64enc }}"
  MONGO_USERNAME: "{{ .Values.mongo.username | b64enc }}"
